#!/usr/bin/env bash
# Precisa excluir a extensão '.meta' do path!
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/berhu/2018-06-29_17-59-58/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/berhu/2018-07-11_13-16-54/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/berhu/2018-07-22_22-22-01/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/berhu/2018-08-06_20-15-06/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/berhu/2018-08-07_19-48-23/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/mse/2018-06-29_13-52-58/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/all_px/mse/2018-08-02_00-51-48/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-07-27_20-32-56/restore/model.fcrn # FIXME: Deu erro! Esse modelo é do tipo 1x1conv?
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-06_09-25-11_1x1conv/restore/model.fcrn*
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-06_11-30-47_1x1conv/restore/model.fcrn*
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-06_20-08-50_1x1conv/restore/model.fcrn*
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-08_11-04-31/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-10_10-07-24/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-07-30_01-30-18/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-12_12-21-08/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-13_10-38-15/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-14_12-57-56/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen_grads/2018-07-30_10-49-02/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen_grads/2018-07-31_09-30-16/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen_grads/2018-08-17_02-48-21/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen_grads/2018-08-20_04-06-01/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-03_13-44-09/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-03_22-14-03/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-07_13-54-34/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-08_10-12-59/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous_city/all_px/berhu/2018-08-03_22-14-10/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous_city/all_px/eigen/2018-08-02_19-54-56/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/all_px/berhu/2018-07-18_15-16-56/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/all_px/berhu/2018-07-19_13-38-29/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/all_px/berhu/2018-07-24_12-48-33/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-07-06_18-07-11/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-07-10_14-01-13/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-07-12_10-58-40/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-07-13_15-06-16/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-09_18-43-38/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-10_16-38-05/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-13_19-03-23/restore/model.fcrn
python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-17_16-52-27/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_discrete/all_px/berhu/2018-07-19_10-18-17/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_discrete/all_px/eigen_grads/2018-07-06_18-32-27/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_discrete/all_px/eigen_grads/2018-07-17_10-51-47/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_discrete/valid_px/berhu/2018-07-12_18-33-06/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_discrete/valid_px/berhu/2018-07-16_15-53-40/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-08_11-04-31/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/berhu/2018-08-10_10-07-24/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-12_12-21-08/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-13_10-38-15/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen/2018-08-14_12-57-56/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/eigen_grads/2018-08-17_02-48-21/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-07_13-54-34/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_continuous/valid_px/mse/2018-08-08_10-12-59/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-09_18-43-38/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-10_16-38-05/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-13_19-03-23/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/kitti_depth/valid_px/berhu/2018-08-17_16-52-27/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-02_16-01-22/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-09_21-47-07/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-12_06-14-00/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-13_10-24-39/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-20_13-10-32/restore/model.fcrn
#python3 predict_nick.py -m test -s kitti_depth --test_split eigen_continuous -r output/fcrn/nyudepth/all_px/berhu/2018-07-23_18-34-45/restore/model.fcrn

# *São do tipo 1x1conv